### ISSUE TITLE
Trying to create database keyword not supported?

### ISSUE THREAD

**Issue by punkouter2021** [TryCatchLearn/DatingApp#3]
What am I missing ? I create a database. Pasted in the connection to the appSetting

Also, will the .net 5 be updated to the final version  ? 

I have gotten the 3.1 version to work

PS C:\Users\punko\downloads\DatingApp\api> dotnet ef database update
Build started...
Build succeeded.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 5.0.0-preview.8.20407.4 initialized 'DataContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: None
System.ArgumentException: Keyword not supported: data source (Parameter 'keyword')
   at Npgsql.NpgsqlConnectionStringBuilder.GetProperty(String keyword)
   at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Keyword not supported: data source (Parameter 'keyword')
PS C:\Users\punko\downloads\DatingApp\api> ^C

**Comment by surajdotnet** [comment]
Hi go to the file `ApplicationServiceExtensions.cs` and Line No 59
and change the following from `options.UseNpgsql(connStr);` to  `options.**UseSqlite**(connStr);`

I tried updating the .net version to 6.0 but I am getting some errors with .net5 its working fine
