### ISSUE TITLE
Cloudinary Issue

### ISSUE THREAD

**Issue by Krivirus** [TryCatchLearn/DatingApp#8]
![image](https://user-images.githubusercontent.com/20033616/106582113-a63e3c00-6569-11eb-9ee7-a64fa5f3087a.png)
Please tell me how can i fix it.

API.Middleware.ExceptionMiddleware[0]
      Cloud name must be specified in Account!
      System.ArgumentException: Cloud name must be specified in Account!
         at CloudinaryDotNet.ApiShared..ctor(Account account)
         at CloudinaryDotNet.Api..ctor(Account account)
         at CloudinaryDotNet.Cloudinary..ctor(Account account)
         at API.Services.PhotoService..ctor(IOptions`1 config) in C:\Users\Krish\Downloads\Project Data\Clozest\API\Services\PhotoService.cs:line 25

**Comment by punkouter2021** [comment]
Need cloudinary settings in your .json file  ?

**Comment by tuxedo007** [comment]
yes, you have to create a Cloudinary account, then put the values in an appsettings.json file.
